### PR TITLE
Add variables support for single node installation

### PR DESCRIPTION
**Pull request by mancubus77**
Original version works only with clustered version, this commit allows to pick variables for single installation as well

### CODE REVIEW

**Comment by hekmon** [comment]
Hello,

Thanks for your PR ! Unfortunately, I would prefer to keep the cluster dashboard for the cluster version of VM as a lot of graphs/panels would not have sens for the single version of VM (think of the 3 different rows for the 3 different VM modules).

Could you consider creating a second dashboard based on this one but specialized for the single version and create a new PR to add it as second dashboard ?

**Comment by mancubus77** [comment]
Actually this makes dashboard applicable for clustered and single node installations, because labels doesn't intersect.

**Comment by hekmon** [comment]
Interesting... I need to setup a single node version to check this out.

What about the values specific of one module, for example cores and vCPU for vmstorage/vminsert in the capacity planing ? Don't you think this could be simplified on the single node version ?

**Comment by mancubus77** [comment]
I run single instance on baremetal single socket E5-2643@3.40GHz server and looks like get right data:
image
these are physical cores, not vCPUs

**Comment by valyala** [comment]
cc'ing @hagen1778 for his input on this pull request

**Comment by hagen1778** [comment]
Can't say much here) It is always right and responsibility of the maintainer to decide. I've checked the PR and it looks fine. Few panels won't work though due to some cluster-specific metric names.
Although, calculations used for planning are different for every application type which is barely applicable for single node version.

**Pull request closed without merging**
